apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: icesi-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nightparker725/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config.icesi-stage.svc.cluster.local:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery.icesi-stage.svc.cluster.local:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: icesi-stage
spec:
  selector:
    app: api-gateway
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
