apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: icesi-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: nightparker725/payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8400
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config.icesi-stage.svc.cluster.local:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery.icesi-stage.svc.cluster.local:8761/eureka"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin.icesi-stage.svc.cluster.local:9411"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: icesi-stage
spec:
  selector:
    app: payment-service
  ports:
    - port: 8400
      targetPort: 8400
  type: ClusterIP
